name: build

on:
  pull_request: {}
  workflow_dispatch: {}
  push: {}

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"

jobs:
  jvm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21

      - uses: gradle/actions/setup-gradle@v3

      - name: Test
        run: ./gradlew build --stacktrace

  android:
    runs-on: ${{ matrix.platform.os }}
    name: ${{ matrix.platform.os }} - KVM ${{ matrix.platform.kvm }}

    strategy:
      fail-fast: false
      matrix:
        platform:
          - os: ubuntu-latest
            kvm: true
          - os: warp-ubuntu-latest-x64-4x
            kvm: true
          - os: warp-ubuntu-latest-arm64-4x
            kvm: false
          - os: ec2-m7a
            kvm: true
          - os: ec2-m6idn
            kvm: true
          - os: ec2-m7gd
            kvm: false
          - os: gha-ubuntu-latest-x64-4x
            kvm: true

    steps:
      - if: ${{ matrix.platform.os }} == 'ubuntu-latest'
        run: curl -H "Metadata:true" "http://169.254.169.254/metadata/instance/compute?api-version=2021-02-01&format=json"
      
      - name: Enable KVM group perms
        if: matrix.platform.kvm
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
          ls /dev/kvm

      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21

      - uses: gradle/actions/setup-gradle@v3

      - name: Run Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedCheck --stacktrace
        env:
          API_LEVEL: 29

  # robovm:
  #   runs-on: macos-latest

  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-java@v4
  #       with:
  #         distribution: 'zulu'
  #         java-version: 21

  #     - uses: gradle/actions/setup-gradle@v3

  #     - name: Run Tests
  #       run: ./gradlew retrofit:robovm-test:robovmTest --stacktrace

  # publish:
  #   runs-on: ubuntu-latest
  #   if: github.repository == 'square/retrofit' && github.ref == 'refs/heads/master'
  #   needs:
  #     - jvm
  #     - android
  #     - robovm

  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-java@v4
  #       with:
  #         distribution: 'zulu'
  #         java-version: 21

  #     - uses: gradle/actions/setup-gradle@v3

  #     - name: Upload Artifacts
  #       run: ./gradlew publish --stacktrace
  #       env:
  #         ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
  #         ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
